// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_bL9PBnr8HhlCz6n6CY0wTd2T5rDNrRI',
    appId: '1:399608882122:web:4495407e519104ea4e6533',
    messagingSenderId: '399608882122',
    projectId: 'image-search-cf544',
    authDomain: 'image-search-cf544.firebaseapp.com',
    storageBucket: 'image-search-cf544.appspot.com',
    measurementId: 'G-R84EREQQG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABa7w3dY__PIFY0mBI6USFmuJlsRLg5Ck',
    appId: '1:399608882122:android:a3248645329b95714e6533',
    messagingSenderId: '399608882122',
    projectId: 'image-search-cf544',
    storageBucket: 'image-search-cf544.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0TQ08wkrbTxfNQDMGRDSwgT1SUBt-lcc',
    appId: '1:399608882122:ios:863590cffab719864e6533',
    messagingSenderId: '399608882122',
    projectId: 'image-search-cf544',
    storageBucket: 'image-search-cf544.appspot.com',
    iosClientId: '399608882122-j50lq72r7tnni6q1bumjs11sn9hdqh0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.imageSearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0TQ08wkrbTxfNQDMGRDSwgT1SUBt-lcc',
    appId: '1:399608882122:ios:f491917b2efa79ec4e6533',
    messagingSenderId: '399608882122',
    projectId: 'image-search-cf544',
    storageBucket: 'image-search-cf544.appspot.com',
    iosClientId: '399608882122-ohsa8h9c44r5rtapaaddan6cuq0l567r.apps.googleusercontent.com',
    iosBundleId: 'com.example.imageSearch.RunnerTests',
  );
}
